import { describe, it, expect, beforeEach } from "vitest";
import { assembleChatFactList, chat } from "./chat";
import type { ChatPerPlyInput } from "./chat";
import type { CoachBackend } from "./backends/types";
import { openDb, createSession, createGame } from "../store/db";

// Task 3 (R1a, fact-gap round): the chat surface previously never saw the
// judge's already-persisted per-ply engine analysis (moves.eval_cp/
// eval_mate/best_move/pv) at all -- it only ever had the bare san list
// (gameSans) and the CURRENT position. This is the load-bearing fix: thread
// the whole game's already-computed analysis in as an optional 4th param, so
// the coach can answer questions about EARLIER moments ("was my opening
// okay?") from real engine facts instead of reasoning about chess itself.
//
// UCI->SAN conversion for bestSan/pvSans happens in the CALLER (manager.ts,
// via the existing pvLine replay discipline) -- assembleChatFactList itself
// only tags each already-SAN entry with a phase and passes it through,
// mirroring the "derived, never hand-computed" rule the rest of this file
// follows, but for a fact this function receives pre-derived.

const moves = (sans: string[]) => sans.map((san, i) => ({ ply: i + 1, san }));

// Real game generated by scripted chess.js self-play (deterministic seed),
// captures biased so material actually drops -- ply 21 still has 24 pieces
// on the board (middlegame), ply 54 is down to 12 (endgame threshold).
const LONG_GAME = [
  "f4", "d6", "Nf3", "e6", "h3", "c6", "c4", "Qf6", "f5", "exf5", "h4", "Qxb2",
  "Bxb2", "f6", "Bxf6", "Nxf6", "Nd4", "Ne4", "Nxf5", "Nxd2", "Nxd2", "Bxf5",
  "Kf2", "Na6", "Qa4", "Bb1", "Rxb1", "Rd8", "Qxc6+", "bxc6", "h5", "Kf7",
  "g4", "Nc7", "e3", "Nd5", "cxd5", "cxd5", "Rb7+", "Kg8", "Rxa7", "h6",
  "Rxg7+", "Bxg7", "Bh3", "Kf7", "Rc1", "Rd7", "Re1", "Ra8", "g5", "Rxa2",
  "gxh6", "Bxh6",
];

// Phase round (2026-07-30, Task 3): a scripted capture sequence where
// majorsAndMinors (queens+rooks+bishops+knights, both colors) is
// deliberately the ONLY Lichess divider predicate that ever fires -- built
// and verified against gamePhases.ts's own exported majorsAndMinors/
// backrankSparse/mixedness at every ply (backrankSparse stays false and
// mixedness stays well under 150 through at least ply 20, so the
// "middlegame" pin below cannot be an accident of a different predicate
// firing first). Captures removing a queen/rook/bishop/knight, counted by
// hand from the SANs (majorsAndMinors starts at 14 = 7 per side):
//   ply9  Nxc6  (white N captures black N)            14 -> 13
//   ply10 bxc6  (pawn recaptures, white N removed)     13 -> 12
//   ply19 Bxf6  (white B captures black N)             12 -> 11
//   ply20 Bxf6  (black B recaptures, white B removed)  11 -> 10  <- majorsAndMinors <= 10: MIDGAME LATCH
//   ply23 Rxe8+ (white R captures black R)             10 -> 9
//   ply24 Qxe8  (black Q recaptures, white R removed)   9 -> 8
//   ply26 Bxf5  (black B captures white B)               8 -> 7
//   ply29 gxf5  (pawn recaptures, black B removed)       7 -> 6  <- majorsAndMinors <= 6: ENDGAME LATCH
const MATERIAL_FORCED_GAME = [
  "e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Nf6", "Nxc6", "bxc6",
  "Bd3", "d5", "exd5", "cxd5", "O-O", "Be7", "Bg5", "O-O", "Bxf6", "Bxf6",
  "Re1", "Re8", "Rxe8+", "Qxe8", "Bf5", "Bxf5", "g4", "a6", "gxf5",
];

describe("assembleChatFactList: perPlyAnalysis (Task 3, R1a)", () => {
  it("is absent when perPly is omitted (no behavior change for existing callers)", () => {
    const facts = assembleChatFactList(moves(LONG_GAME), {});
    expect(facts.perPlyAnalysis).toBeUndefined();
  });

  it("carries SAN best moves through untouched and tags ply 1 as opening (no divider predicate fires this early)", () => {
    const perPly = [
      { ply: 1, san: "f4", evalCp: 30, evalMate: null, bestSan: "d5", pvSans: ["d5", "Nf3"] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis).toEqual([
      { ply: 1, san: "f4", evalCp: 30, evalMate: null, bestSan: "d5", pvSans: ["d5", "Nf3"], phase: "opening" },
    ]);
  });

  it("tags the ply where majorsAndMinors first drops to 10 or fewer as middlegame (MATERIAL_FORCED_GAME ply 20)", () => {
    const perPly = [
      { ply: 20, san: "Bxf6", evalCp: -50, evalMate: null, bestSan: "Re1", pvSans: ["Re1"] },
    ];
    const facts = assembleChatFactList(moves(MATERIAL_FORCED_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].phase).toBe("middlegame");
  });

  // Union review F2 (2026-07-30 fix wave): the pin above asserts the label
  // AT the boundary but never the boundary itself -- a wrong threshold
  // (e.g. MIDGAME_MAJORS_MINORS_MAX drifted from 10 to 12) would move the
  // real latch from ply 20 to ply 10 and this suite would stay green,
  // because nothing ever checked that ply 19 -- one before the real latch
  // -- is still "opening". This closes that: it fails on the ply-12 mutant
  // and passes on shipped code.
  it("ply 19 -- one before the midgame latch -- is still opening, not a moved boundary", () => {
    const perPly = [
      { ply: 19, san: "Bxf6", evalCp: -40, evalMate: null, bestSan: "Bxf6", pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(MATERIAL_FORCED_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].phase).toBe("opening");
  });

  it("tags the ply where majorsAndMinors first drops to 6 or fewer as endgame (MATERIAL_FORCED_GAME ply 29)", () => {
    const perPly = [
      { ply: 29, san: "gxf5", evalCp: 400, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(MATERIAL_FORCED_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].phase).toBe("endgame");
  });

  it("tags multiple plies independently in one call", () => {
    const perPly = [
      { ply: 1, san: "e4", evalCp: 30, evalMate: null, bestSan: "e4", pvSans: [] },
      { ply: 20, san: "Bxf6", evalCp: -50, evalMate: null, bestSan: "Re1", pvSans: ["Re1"] },
      { ply: 29, san: "gxf5", evalCp: 400, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(MATERIAL_FORCED_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis!.map((p) => p.phase)).toEqual(["opening", "middlegame", "endgame"]);
  });

  it("a null bestSan/empty pvSans (no persisted eval yet for that ply) passes through as-is", () => {
    const perPly = [
      { ply: 54, san: "Bxh6", evalCp: null, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].bestSan).toBeNull();
    expect(facts.perPlyAnalysis![0].pvSans).toEqual([]);
  });

  it("carries an optional then claim through untouched (forward-prediction round)", () => {
    const perPly = [
      { ply: 1, san: "f4", evalCp: 30, evalMate: null, bestSan: "d5", pvSans: ["d5", "Nf3"], then: "you win a pawn" },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].then).toBe("you win a pawn");
  });
});

// Task 3b (R2, voice-enforcement round, 2026-07-22): factsForModel is
// private, so this asserts against the actual prompt string chat() sends
// the backend, the same pattern chat.hintFocus.test.ts/chat.test.ts's own
// prompt-inspection tests already use. evalCp/evalMate are SIDE-TO-MOVE
// signed as of the position AFTER the ply (same convention
// turningPoints.ts's buildDeltaSeries documents) -- an ODD ply's stored
// value is black-perspective and must be negated to reach the fixed
// "player is always white" read; an EVEN ply's is already white-perspective.
function fakeBackend(generate: (prompt: string, timeoutMs: number) => Promise<string>): CoachBackend {
  return {
    name: "fake",
    async available() {
      return true;
    },
    generate,
  };
}

const GAME = ["e4", "e5"];
const gameMoves = (sans: string[]) => sans.map((san, i) => ({ ply: i + 1, san }));

async function capturePerPlyPrompt(perPly: ChatPerPlyInput[]): Promise<string> {
  const facts = assembleChatFactList(gameMoves(GAME), { mode: "review" }, undefined, perPly);
  let capturedPrompt = "";
  const backend = fakeBackend(async (prompt) => {
    capturedPrompt = prompt;
    return "e4 is a fine start for you.";
  });
  const sessionId = createSession();
  const gameId = createGame(sessionId, "maia-1100");
  await chat("how did this go?", [], facts, backend, { gameId, ply: 1, kind: "chat" });
  return capturedPrompt;
}

describe("factsForModel — perPlyAnalysis's evalCp/evalMate sanitize into a qualitative 'read' bucket (Task 3b)", () => {
  beforeEach(() => {
    openDb(":memory:");
  });

  it("drops evalCp/evalMate (and any eval-named key) from the model projection, while the raw ChatFactList still carries the numbers", async () => {
    const perPly: ChatPerPlyInput[] = [
      { ply: 1, san: "e4", evalCp: 20, evalMate: null, bestSan: "e4", pvSans: [] },
    ];
    const facts = assembleChatFactList(gameMoves(GAME), { mode: "review" }, undefined, perPly);
    expect(facts.perPlyAnalysis?.[0].evalCp).toBe(20); // raw facts: numbers stay, for validation + F40 trace

    const prompt = await capturePerPlyPrompt(perPly);
    expect(prompt).toContain('"read"');
    expect(prompt).not.toContain('"evalCp"');
    expect(prompt).not.toContain('"evalMate"');
  });

  it("a small even-ply cp edge reads as 'even'", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: 20, evalMate: null, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain('"read":"even"');
  });

  it("a moderate even-ply positive cp reads as 'you're a bit better'", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: 150, evalMate: null, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read":"you're a bit better"`);
  });

  it("a large even-ply positive cp reads as 'you're much better'", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: 500, evalMate: null, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read":"you're much better"`);
  });

  it("a large even-ply negative cp reads as 'she's much better'", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: -500, evalMate: null, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read":"she's much better"`);
  });

  it("an ODD-ply negative cp (black's own stored perspective) negates to a white-favorable read", async () => {
    // Ply 1 is white's own move -- the stored eval afterward is from BLACK's
    // (side-to-move) perspective, so a stored -150 means white (the player)
    // is actually up 150: negation must run before bucketing.
    const prompt = await capturePerPlyPrompt([{ ply: 1, san: "e4", evalCp: -150, evalMate: null, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read":"you're a bit better"`);
  });

  it("an even-ply positive evalMate reads as 'mate for you in N'", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: null, evalMate: 3, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read":"mate for you in 3"`);
  });

  it("an even-ply negative evalMate reads as 'mate against you in N'", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: null, evalMate: -2, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read":"mate against you in 2"`);
  });

  it("an odd-ply evalMate is negated the same way evalCp is", async () => {
    // Ply 1: stored -4 is black's own perspective (black about to be mated
    // in 4 is wrong framing -- stored is black delivers in -4, i.e. black is
    // BEING mated) -- negating gives white (the player) mates in 4.
    const prompt = await capturePerPlyPrompt([{ ply: 1, san: "e4", evalCp: null, evalMate: -4, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read":"mate for you in 4"`);
  });

  it("no persisted eval yet for that ply (both null) reads as a plain no-data statement, never a number", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: null, evalMate: null, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain('"read":"no read yet"');
  });
});

// B4b (2026-07-27, coach-truth-speed round): perPlyForModel's ply-scoping.
// The whole-game perPlyAnalysis list is still fully CARRIED (assembleChatFactList
// ships every ply so the trace JSON stays complete for the Lab) but the
// MODEL-facing projection now ships full detail (bestSan/pvSans/phase,
// alongside san/read) only for plies in the union of turning-point plies,
// the focused ply +/- 2, the pending move's own ply, and the last
// RECENT_PLY_WINDOW (12) plies -- everything else collapses to
// {ply, san, read}. LONG_GAME (54 plies, imported above) puts ply 3 and
// ply 5 both well outside the last-12 window (43-54), so a bare recency
// check alone would collapse both.
describe("perPlyForModel — ply-scoping (B4b)", () => {
  beforeEach(() => {
    openDb(":memory:");
  });

  it("a turning point outside the recent window still ships full detail", async () => {
    const perPly: ChatPerPlyInput[] = [
      { ply: 5, san: "h4", evalCp: -20, evalMate: null, bestSan: "Nf3", pvSans: ["Nf3", "Nc6"] },
      { ply: 54, san: "Bxh6", evalCp: 400, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(
      moves(LONG_GAME),
      {},
      [{ ply: 5, san: "h4", label: "inaccuracy" }],
      perPly
    );

    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "h4 grabbed some space for you.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("how did move 5 go?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    expect(capturedPrompt).toContain('"bestSan":"Nf3"');
    expect(capturedPrompt).toContain('"pvSans":["Nf3","Nc6"]');
  });

  it("an ordinary early ply outside every window collapses to ply/san/bestSan/read -- pvSans/phase still dropped", async () => {
    const perPly: ChatPerPlyInput[] = [
      { ply: 3, san: "Nf3", evalCp: 10, evalMate: null, bestSan: "KEEP-BESTSAN", pvSans: ["DROP-PV"] },
      { ply: 54, san: "Bxh6", evalCp: 400, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);

    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "e4 opens things up nicely for you.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("how did the opening go?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    expect(capturedPrompt).toContain('"ply":3');
    // B4c (2026-07-28, coach-truth-speed round, regression fix): a collapsed
    // ply must still carry bestSan -- dropping it entirely (the shipped
    // regression) meant a question about any ply outside the last
    // RECENT_PLY_WINDOW plies could never be answered with a concrete better
    // move (owner's game-150 thumbs-down: asked about ply 27/28 in a 91-ply
    // game, ~37 plies back, and the coach could not say). pvSans/phase are
    // still the ONLY things dropped on collapse -- that's the actual token
    // saving this round's B4b banked, and this test guards it doesn't quietly
    // widen back out.
    expect(capturedPrompt).toContain('"bestSan":"KEEP-BESTSAN"');
    expect(capturedPrompt).not.toContain("DROP-PV");
    expect(capturedPrompt).not.toMatch(/"phase":"(opening|middlegame|endgame)"[^}]*"ply":3/);
  });

  it("a ply outside the recent window still carries bestSan (token-shape guard against re-dropping it)", async () => {
    // Deliberately identical setup to the collapse test above, phrased as
    // its own named case per the round's required test list -- a future
    // change that special-cases away bestSan again fails THIS test even if
    // the collapse test above is edited or removed.
    const perPly: ChatPerPlyInput[] = [
      { ply: 3, san: "Nf3", evalCp: 10, evalMate: null, bestSan: "Nc6", pvSans: ["Nc6", "Bc4"] },
      { ply: 54, san: "Bxh6", evalCp: 400, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);

    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "e4 opens things up nicely for you.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("what should you have played at move 3 instead?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    expect(capturedPrompt).toContain('"ply":3');
    expect(capturedPrompt).toContain('"bestSan":"Nc6"');
  });
});

// Forward-prediction round (2026-07-28): perPlyForModel's then/pv-depth
// rules. Collapsed plies carry then only when she deviated from best (the
// "what did i miss" set -- measured +363 tokens on real 91-ply game 150 vs
// +508 for then-everywhere); full-detail plies carry it whenever derivable,
// and their pvSans deepen from 2 to 6 so cookie can walk a real line.
describe("perPlyForModel — then + pv depth (forward-prediction round)", () => {
  beforeEach(() => {
    openDb(":memory:");
  });

  async function capture(perPly: ChatPerPlyInput[], message = "how did this go?") {
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "that stretch went fine for you.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat(message, [], facts, backend, { gameId, ply: 1, kind: "chat" });
    return capturedPrompt;
  }

  it("a collapsed ply where she deviated from best carries its then claim", async () => {
    const prompt = await capture([
      { ply: 3, san: "Nf3", evalCp: 10, evalMate: null, bestSan: "d4", pvSans: ["d4"], then: "you win a pawn" },
      { ply: 54, san: "Bxh6", evalCp: 0, evalMate: null, bestSan: null, pvSans: [] },
    ]);
    expect(prompt).toContain('"ply":3');
    expect(prompt).toContain('"then":"you win a pawn"');
  });

  it("a collapsed ply where she PLAYED the best move drops then", async () => {
    const prompt = await capture([
      { ply: 3, san: "Nf3", evalCp: 10, evalMate: null, bestSan: "Nf3", pvSans: ["Nf3"], then: "you win a pawn" },
      { ply: 54, san: "Bxh6", evalCp: 0, evalMate: null, bestSan: null, pvSans: [] },
    ]);
    expect(prompt).not.toContain('"then"');
  });

  it("a full-detail ply carries then even when she played the best move", async () => {
    const prompt = await capture([
      { ply: 54, san: "Bxh6", evalCp: 0, evalMate: null, bestSan: "Bxh6", pvSans: ["Bxh6"], then: "you win a pawn" },
    ]);
    expect(prompt).toContain('"then":"you win a pawn"');
  });

  it("a full-detail ply now ships up to six pv moves, not two", async () => {
    const prompt = await capture([
      {
        ply: 54, san: "Bxh6", evalCp: 0, evalMate: null, bestSan: "PV1",
        pvSans: ["PV1", "PV2", "PV3", "PV4", "PV5", "PV6", "PV7"],
      },
    ]);
    expect(prompt).toContain('"pvSans":["PV1","PV2","PV3","PV4","PV5","PV6"]');
    expect(prompt).not.toContain("PV7");
  });

  it("naming a move in the message promotes its plies to full detail (pvSans ship)", async () => {
    const prompt = await capture(
      [
        { ply: 27, san: "Nxd2", evalCp: 0, evalMate: null, bestSan: "Bxf5", pvSans: ["Bxf5", "g4", "Be4"], then: "you win a pawn" },
        { ply: 54, san: "Bxh6", evalCp: 0, evalMate: null, bestSan: null, pvSans: [] },
      ],
      "what should i have done on move 14"
      // move 14 -> plies 27, 28 (and raw 14): ply 27 sits outside the
      // last-12 window of the 54-ply LONG_GAME and has no turning point, so
      // WITHOUT promotion it would collapse and drop its pvSans.
    );
    expect(prompt).toContain('"pvSans":["Bxf5","g4","Be4"]');
  });

  it("the same ply stays collapsed when no move number is mentioned", async () => {
    const prompt = await capture(
      [
        { ply: 27, san: "Nxd2", evalCp: 0, evalMate: null, bestSan: "Bxf5", pvSans: ["Bxf5", "g4", "Be4"], then: "you win a pawn" },
        { ply: 54, san: "Bxh6", evalCp: 0, evalMate: null, bestSan: null, pvSans: [] },
      ],
      "how did this go?"
    );
    expect(prompt).not.toContain('"pvSans":["Bxf5","g4","Be4"]');
  });

  it("validateChat flags an invented mate-in-N and the reply falls back through the regen discipline", async () => {
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, [
      { ply: 54, san: "Bxh6", evalCp: null, evalMate: 2, bestSan: null, pvSans: [] },
    ]);
    const outputs = ["you had mate in 7 there.", "you had mate in 7 there."];
    let calls = 0;
    const backend = fakeBackend(async () => outputs[calls++]);
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    const result = await chat("how did the end go?", [], facts, backend, { gameId, ply: 54, kind: "chat" });
    expect(result.source).toBe("template");
    expect(result.cause).toBe("validation-failed");
  });
});

// Highlight-a-move (Task 8): a ply she flagged during live play must ship
// full detail regardless of age, or "why did I highlight this?" hits the
// same RECENT_PLY_WINDOW wall the turning-point/focus cases above already
// get an exemption from. Seeded directly into fullDetailPlies (perPlyForModel),
// NOT routed through facts.turningPoints -- turningPoints' sans fold into
// allowedSans for validateChat, and a highlighted ply that never was an
// actual turning point would drift that allow-list.
describe("perPlyForModel — a highlighted ply ships full detail (Task 8)", () => {
  beforeEach(() => {
    openDb(":memory:");
  });

  it("a highlighted ply outside the recent window still ships pvSans/phase", async () => {
    const perPly: ChatPerPlyInput[] = [
      { ply: 3, san: "Nf3", evalCp: 10, evalMate: null, bestSan: "Nc6", pvSans: ["Nc6", "Bc4"] },
      { ply: 54, san: "Bxh6", evalCp: 400, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly, undefined, [3]);

    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "here's the position at the moment you flagged.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    // The message names NO move number on purpose. Once the forward-prediction
    // round's mentioned-ply promotion merged in, "why did I highlight move 2?"
    // promoted ply 3 by itself, so this test and its control below both passed
    // without the highlight seed doing any work. A neutral message leaves
    // highlightedPlies as the only path to full detail.
    await chat("why did i flag that one?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    expect(capturedPrompt).toContain('"ply":3');
    expect(capturedPrompt).toContain('"bestSan":"Nc6"');
    expect(capturedPrompt).toContain('"pvSans":["Nc6","Bc4"]');
  });

  it("without highlightedPlies, the same ply collapses (no behavior change for existing callers)", async () => {
    const perPly: ChatPerPlyInput[] = [
      { ply: 3, san: "Nf3", evalCp: 10, evalMate: null, bestSan: "Nc6", pvSans: ["Nc6", "Bc4"] },
      { ply: 54, san: "Bxh6", evalCp: 400, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.highlightedPlies).toBeUndefined();

    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "e4 opens things up nicely for you.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("why did i flag that one?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    expect(capturedPrompt).not.toContain("Bc4");
  });
});

// Missed-win round (2026-07-28): shared real-game fixture (game 150,
// 2026-07-28, her real 91-ply win). Repeated per repo convention.
const GAME150_SANS = [
  "d4","d5","c3","c6","b3","e6","e3","Nf6","Bd2","Be7","Bd3","Bd7","Nf3","O-O","O-O","c5",
  "dxc5","Bxc5","b4","Qe7","bxc5","Qxc5","Qb3","Nc6","c4","Nh5","cxd5","Ne7","Bb4","Ba4",
  "Qxa4","Qc6","dxc6","f5","Bxe7","Rfe8","cxb7","g5","bxa8=Q","Rxa8","Bxg5","Nf4","exf4","Rc8",
  "Qxa7","Ra8","Qxa8+","Kg7","Ne5","h6","Be7","h5","h4","Kh6","Nf7+","Kg6","Nh8+","Kh7",
  "Nf7","Kg7","Nh6","e5","Qf8+","Kh7","Qh8+","Kg6","Ng8","exf4","g3","f3","Nd2","Kf7",
  "Qh7+","Ke6","Bd8","Ke5","Bxf5","Kd4","Rfe1","Kc3","Nxf3","Kc4","Rab1","Kd5","Qxh5","Kd6",
  "Qh6+","Kd5","Be7","Kc4","Qc6#",
].map((san, i) => ({ ply: i + 1, san }));

describe("perPlyForModel — missed-win turning point ships full detail (missed-win round, 2026-07-28)", () => {
  beforeEach(() => {
    openDb(":memory:");
  });

  // Regression pin: pins the EXISTING fullDetailPlies fold (facts.turningPoints
  // ply -> full detail, see perPlyForModel) against the missed-win shape
  // specifically -- proving the "one emission point lights up every surface"
  // design claim for chat without adding a second mechanism. perPlyForModel
  // itself isn't exported (same convention as every other test in this file),
  // so this goes through the real chat() call and inspects the captured
  // model-facing prompt, exactly like the ply-scoping tests above.
  it("a missed-win turning point's ply ships full detail however old it is", async () => {
    const gameMoves = GAME150_SANS; // shared fixture, declared above
    const perPly: ChatPerPlyInput[] = gameMoves.map((m) => ({
      ply: m.ply, san: m.san, evalCp: 0, evalMate: null, bestSan: m.ply === 55 ? "Qh8#" : null, pvSans: m.ply === 55 ? ["Qh8#"] : [],
    }));
    const facts = assembleChatFactList(
      gameMoves,
      {},
      [{ ply: 55, san: "Nf7+", label: "missed mate" }],
      perPly
    );

    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "the missed mate on move 28 is the story of this game.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("what happened on move 28?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    expect(capturedPrompt).toContain('"ply":55');
    expect(capturedPrompt).toContain('"pvSans":["Qh8#"]'); // full detail, not the collapsed shape
  });
});

describe("the shared phase timeline — nearly-bare side (missed-win round, 2026-07-28; converged onto src/review/gamePhases.ts, phase round 2026-07-30)", () => {
  it("reads a nearly-bare board as endgame regardless of total piece count, and stays opening until a real Lichess predicate fires (game 150)", () => {
    const gameMoves = GAME150_SANS; // shared fixture from the plan header
    const perPly: ChatPerPlyInput[] = [5, 21, 55].map((ply) => ({
      ply, san: gameMoves[ply - 1].san, evalCp: null, evalMate: null, bestSan: null, pvSans: [],
    }));
    const facts = assembleChatFactList(gameMoves, {}, [], perPly);
    const phases = Object.fromEntries(facts.perPlyAnalysis!.map((p) => [p.ply, p.phase]));
    expect(phases[5]).toBe("opening");
    // Board facts at ply 21 (verified against gamePhases.ts's own exported
    // predicates): majorsAndMinors=13 (> 10), backrankSparse=false,
    // mixedness=130 (<= 150) -- no Lichess divider predicate has fired yet.
    // The OLD derivePhase's "ply > 20 means middlegame" pin encoded a
    // fallback the shared timeline does not have; this game's real midgame
    // latch is ply 24 (backrankSparse trips first).
    expect(phases[21]).toBe("opening");
    // 17 pieces total on the board at ply 55, but black is down to a lone
    // king (no non-pawn, non-king piece left) -- phase.ts's nearly-bare
    // override, carried through gamePhases.ts's PhaseTimeline, tags this
    // endgame regardless of majorsAndMinors/backrankSparse/mixedness.
    expect(phases[55]).toBe("endgame");
  });
});

// Integration-round fix (2026-07-30): phasesForGame.phaseAt returns null
// when there is no board to prove a phase from (gameSans absent or empty --
// see src/review/gamePhases.ts's own header comment, "Important 5 / union
// F1"). assembleChatFactList tags every perPlyAnalysis entry with
// phases.phaseAt(p.ply), so a caller that hands perPly entries while
// gameMoves itself is empty (the one situation where hasBoard is false)
// produces perPlyAnalysis entries whose phase is genuinely unprovable. The
// debrief round already stopped fabricating "opening" for this exact case;
// the coach must not reintroduce the same lie on the other side of the
// seam by leaking a literal "phase":null (or any placeholder) into the
// model-facing prompt. This must fail for a real board (a game with real
// moves, seen elsewhere in this file, always has a provable phase).
describe("an unprovable phase (no board to derive it from) is omitted, never fabricated or leaked as a placeholder", () => {
  beforeEach(() => {
    openDb(":memory:");
  });

  it("perPlyAnalysis.phase is null, not a fabricated phase string, when gameMoves is empty", () => {
    const perPly: ChatPerPlyInput[] = [
      { ply: 1, san: "e4", evalCp: 0, evalMate: null, bestSan: null, pvSans: [] },
    ];
    // gameMoves is deliberately empty -- the one condition (Important 5 /
    // union F1) under which phasesForGame has no board to replay at all.
    const facts = assembleChatFactList([], {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].phase).toBeNull();
  });

  it("the model-facing prompt never carries a phase key -- and never the strings null/undefined/none -- for a ply with no provable phase", async () => {
    const perPly: ChatPerPlyInput[] = [
      { ply: 1, san: "e4", evalCp: 0, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList([], {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].phase).toBeNull(); // fixture sanity: this really is the unprovable case

    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "e4 opens things up nicely for you.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("how did i do?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    // The whole point: the coach's fact list must OMIT phase for this ply,
    // not state it falsely and not state it as an empty/placeholder value.
    expect(capturedPrompt).not.toContain('"phase"');
    expect(capturedPrompt).not.toMatch(/"phase"\s*:\s*"?(null|undefined|none)"?/i);
    // m4 (2026-07-30 integration review): the negative assertion above is
    // satisfied just as well by perPlyAnalysis disappearing from the
    // projection entirely -- exactly the kind of change factsForModel has
    // taken twice before (B4b, B4c). This positive assertion pins that the
    // section this ply's phase key is omitted FROM still ships.
    expect(capturedPrompt).toContain('"perPlyAnalysis"');
  });
});

// Round 3 (Q2/B1, Task 5): factsForModel is private -- same "assert against
// the actual prompt string" discipline this file already uses for the
// evalCp/evalMate sanitize rule above. The hint shelf's own evalCp must be
// sanitized the same way (never a raw centipawn number); evalMate is a
// distance, not a score, so it is allowed to read as a number.
describe("factsForModel — the hint shelf renders as its own model-facing section (Q2/B1)", () => {
  beforeEach(() => {
    openDb(":memory:");
  });

  it("the model-facing facts render the hint shelf as its own labeled section", async () => {
    const START_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
    const facts = assembleChatFactList(
      [],
      { mode: "live" },
      undefined, undefined, undefined, undefined,
      {
        fen: START_FEN,
        facts: {
          bestUci: "g1f3", // Nf3 -- distinct from a pawn push, unambiguous SAN
          pv: ["g1f3"],
          evalCp: null,
          evalMate: 3,
          trade: false,
          escalated: false,
          verified: true, // a real, player-initiated deep hint
        },
      }
    );
    expect(facts.hintFindings?.bestSan).toBe("Nf3"); // fixture sanity

    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "there's something forcing here for you.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("why is that the move?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    expect(capturedPrompt).toMatch(/hint engine.*verified line for this position/i);
    expect(capturedPrompt).toMatch(/Nf3/);
    expect(capturedPrompt).toMatch(/mate.*3/i);
  });

  it("never leaks the shelf's raw evalCp as a centipawn number", async () => {
    const START_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
    const facts = assembleChatFactList(
      [],
      { mode: "live" },
      undefined, undefined, undefined, undefined,
      {
        fen: START_FEN,
        facts: { bestUci: "g1f3", pv: ["g1f3"], evalCp: 234, evalMate: null, trade: false, escalated: false, verified: true },
      }
    );
    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "that develops nicely for you.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("why is that the move?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    expect(capturedPrompt).not.toContain("234");
  });

  // Round 3 whole-branch review (2026-08-03), Important finding 1: the shelf
  // is populated by TWO different producers with very different confidence
  // -- computeHint's deep, verified, player-initiated search, and
  // computePositionView's fast (500ms, single-PV, no verification retry)
  // bounded read that fires on every live chat message with no matching
  // prior hint (the COMMON case). Before this fix, hintFindingsForModel
  // labeled both "verified... deep multipv search, trust this over your own
  // reasoning" regardless of which producer filled the shelf -- exactly
  // backwards for the common fast-path case. The `verified` provenance flag
  // (HintFacts/HintFindings) now drives the wording: only a real deep hint
  // may claim "verified"/"trust over your own reasoning"; the fast path
  // must say something honest instead and must never imply its bestSan is
  // verified-best.
  it("an UNVERIFIED shelf entry (fast position-view path) is never labeled verified or told to be trusted over the model's own reasoning", async () => {
    const START_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
    const facts = assembleChatFactList(
      [],
      { mode: "live" },
      undefined, undefined, undefined, undefined,
      {
        fen: START_FEN,
        facts: {
          bestUci: "g1f3",
          pv: ["g1f3"],
          evalCp: null,
          evalMate: 3,
          trade: false,
          escalated: false,
          verified: false, // computePositionView's fast, unverified read
        },
      }
    );
    expect(facts.hintFindings?.bestSan).toBe("Nf3"); // fixture sanity

    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "there's something forcing here for you.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("why is that the move?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    expect(capturedPrompt).not.toMatch(/verified/i);
    expect(capturedPrompt).not.toMatch(/trust this over your own reasoning/i);
    // The engine fact itself must still reach the model -- just honestly framed.
    expect(capturedPrompt).toMatch(/Nf3/);
  });

  it("a VERIFIED shelf entry (deep hint path) keeps the verified/trust-over-your-own-reasoning framing", async () => {
    const START_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
    const facts = assembleChatFactList(
      [],
      { mode: "live" },
      undefined, undefined, undefined, undefined,
      {
        fen: START_FEN,
        facts: {
          bestUci: "g1f3",
          pv: ["g1f3"],
          evalCp: null,
          evalMate: 3,
          trade: false,
          escalated: false,
          verified: true,
        },
      }
    );
    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "there's something forcing here for you.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("why is that the move?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    expect(capturedPrompt).toMatch(/verified/i);
    expect(capturedPrompt).toMatch(/trust this over your own reasoning/i);
  });
});

// Task 2 (2026-08-28, game-192 RCA): the deep hint runs MultiPV=3 but, before
// this task, dropped candidates 2-3 on the floor entirely -- nothing in the
// fact list could say "these moves are near-equal," so the coach model
// fabricated reasons for its pick (real game 192). `margin` is that missing
// fact, in words only (voice rule: no raw eval numbers reach the model).
// Fixture cps 810/809/760 per the controller's pre-flight ruling: the
// close-call sentence names only candidates within HINT_CLOSE_CALL_CP of the
// BEST candidate's own cp (809 qualifies at a 1cp gap, 760 does not at a
// 50cp gap), not every candidate the shelf happens to carry.
describe("hintFindingsForModel — candidates and the margin projection (Task 2, game-192 RCA)", () => {
  beforeEach(() => {
    openDb(":memory:");
  });

  const START_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
  // g1f3 (Nf3, 810) is best; b1c3 (Nc3, 809) is within HINT_CLOSE_CALL_CP
  // (35) of it; e2e4 (e4, 760) is not (50cp away).
  const closeCallCandidates = [
    { uci: "g1f3", evalCp: 810, evalMate: null },
    { uci: "b1c3", evalCp: 809, evalMate: null },
    { uci: "e2e4", evalCp: 760, evalMate: null },
  ];
  // Same three moves, but spaced out (gap 110 between best and second) so
  // no close call should ever fire.
  const spreadCandidates = [
    { uci: "g1f3", evalCp: 810, evalMate: null },
    { uci: "b1c3", evalCp: 700, evalMate: null },
    { uci: "e2e4", evalCp: 650, evalMate: null },
  ];

  // JSON.stringify escapes the literal `"` inside 'is "best"' as `\"`, so a
  // naive `[^"]*` capture truncates at that escaped quote. Match escaped
  // sequences too, then let JSON.parse do the real unescaping.
  function extractMargin(prompt: string): string | undefined {
    const m = prompt.match(/"margin":"((?:\\.|[^"\\])*)"/);
    return m ? (JSON.parse(`"${m[1]}"`) as string) : undefined;
  }

  function hintCandidateFacts(candidates: typeof closeCallCandidates, evalCp: number) {
    return {
      fen: START_FEN,
      facts: {
        bestUci: "g1f3",
        pv: ["g1f3"],
        evalCp,
        evalMate: null,
        trade: false,
        escalated: false,
        verified: true,
        candidates,
      },
    };
  }

  it("hintFindings.candidates is san-converted with each candidate's own cp, and each candidate san joins allowedSans", () => {
    const facts = assembleChatFactList(
      [],
      { mode: "live" },
      undefined, undefined, undefined, undefined,
      hintCandidateFacts(closeCallCandidates, 100)
    );
    expect(facts.hintFindings?.candidates).toEqual([
      { san: "Nf3", evalCp: 810 },
      { san: "Nc3", evalCp: 809 },
      { san: "e4", evalCp: 760 },
    ]);
    // Requirement: candidate sans join the allowedSans set in the fold, so a
    // model naming any of them is recognized as a real, legal move. Note:
    // at this fen every candidate is ALSO already a member of currentFen's
    // own legalSans (unconditionally folded in above, independent of any
    // hint) -- this fold matters for the case a candidate's matchFen is a
    // past FOCUS position instead, where the model may be discussing that
    // moment specifically. Asserted here as a direct membership check
    // (rather than through validateChat) because a separate, unrelated
    // voice-notation rule bans ALL raw SAN tokens in a reply regardless of
    // legality -- see checkVoice's own comment -- so a full validateChat()
    // call against literal notation text can never return ok:true and would
    // not isolate this fold's own contribution.
    expect(facts.allowedSans).toEqual(expect.arrayContaining(["Nf3", "Nc3", "e4"]));
  });

  it('(a) a close call with an undecided position reads "close call: Nf3 and Nc3 are about equally strong here..." and nothing about the position being decided', async () => {
    const facts = assembleChatFactList(
      [],
      { mode: "live" },
      undefined, undefined, undefined, undefined,
      hintCandidateFacts(closeCallCandidates, 100) // |evalCp| well under HINT_DECIDED_CP
    );
    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "either developing move works well here.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("why this move?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    const margin = extractMargin(capturedPrompt);
    expect(margin).toBe(
      "close call: Nf3 and Nc3 are about equally strong here. the engine's pick between near-equal moves can change between looks; that is search variance, not a contradiction."
    );
    expect(capturedPrompt).not.toMatch(/decisively ahead/);
  });

  it('(b) a close call in an already-decided position ALSO includes the "decisively ahead" sentence', async () => {
    const facts = assembleChatFactList(
      [],
      { mode: "live" },
      undefined, undefined, undefined, undefined,
      hintCandidateFacts(closeCallCandidates, 810) // |evalCp| >= HINT_DECIDED_CP (500)
    );
    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "either developing move works well here.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("why this move?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    const margin = extractMargin(capturedPrompt);
    expect(margin).toBe(
      "close call: Nf3 and Nc3 are about equally strong here. the engine's pick between near-equal moves can change between looks; that is search variance, not a contradiction. " +
        'the position is already decisively ahead for the side to move; several moves keep the win, so which winning move is "best" matters much less than usual.'
    );
  });

  // Voice rule (binding): margin never leaks a raw eval/cp number (810,
  // 809, 760, or the HINT_CLOSE_CALL_CP/HINT_DECIDED_CP thresholds
  // themselves) -- words only. Candidate SANs (e.g. "Nf3") are chess
  // notation, not eval numbers, and are the exact copy the brief itself
  // prescribes -- so this checks for absence of the actual NUMERIC VALUES
  // that could leak (an eval or a threshold), rather than a blanket
  // "no digit anywhere" bar that no real SAN could ever pass (every
  // non-castling SAN includes a destination rank digit).
  it("(c) the margin string never leaks a raw eval/cp number (voice rule: words only)", async () => {
    const facts = assembleChatFactList(
      [],
      { mode: "live" },
      undefined, undefined, undefined, undefined,
      hintCandidateFacts(closeCallCandidates, 810)
    );
    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "either developing move works well here.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("why this move?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    const margin = extractMargin(capturedPrompt);
    expect(margin).toBeTruthy();
    for (const rawNumber of ["810", "809", "760", "35", "500"]) {
      expect(margin).not.toContain(rawNumber);
    }
  });

  it("(d) a wide gap in an undecided position never emits a margin at all", async () => {
    const facts = assembleChatFactList(
      [],
      { mode: "live" },
      undefined, undefined, undefined, undefined,
      hintCandidateFacts(spreadCandidates, 100) // gap 110 > HINT_CLOSE_CALL_CP, |evalCp| < HINT_DECIDED_CP
    );
    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "Nf3 develops nicely here.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("why this move?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    expect(capturedPrompt).not.toContain('"margin"');
    expect(capturedPrompt).not.toMatch(/close call/);
    expect(capturedPrompt).not.toMatch(/decisively ahead/);
  });

  // Fix round 1, Finding 1 (review, Important): the naive `cands = h
  // .candidates.filter((c) => c.evalCp !== null)` silently drops a
  // mate-scored TOP line, so with candidates [mate-in-3, cp 300, cp 295]
  // the old code named the two cp-scored runners-up "close" to each other
  // -- while a mate sits on the board and neither of them is even the
  // best move. The true best candidate (index 0 of the UNFILTERED array)
  // not surviving the evalCp!==null filter is the signal that no
  // candidate-vs-candidate cp comparison is meaningful here.
  it("Fix 1: a mate-scored best candidate suppresses the close-call clause entirely, even when the cp-scored runners-up are close to each other", async () => {
    const facts = assembleChatFactList(
      [],
      { mode: "live" },
      undefined, undefined, undefined, undefined,
      {
        fen: START_FEN,
        facts: {
          bestUci: "g1f3",
          pv: ["g1f3"],
          evalCp: null,
          evalMate: 3,
          trade: false,
          escalated: false,
          verified: true,
          candidates: [
            { uci: "g1f3", evalCp: null, evalMate: 3 }, // the true best: a mate, not cp-scored
            { uci: "b1c3", evalCp: 300, evalMate: null },
            { uci: "e2e4", evalCp: 295, evalMate: null }, // 5cp from b1c3 -- would wrongly read as "close"
          ],
        },
      }
    );
    // Fixture sanity, matching the review's own described scenario exactly.
    expect(facts.hintFindings?.bestSan).toBe("Nf3");

    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "there's a forced mate here.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("why this move?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    expect(capturedPrompt).toMatch(/verified forced mate in 3/i); // score is still the mate, unaffected
    expect(capturedPrompt).not.toMatch(/close call/i);
    expect(capturedPrompt).not.toMatch(/Nc3 and e4/);
  });

  // Fix round 1, Finding 2 (controller ruling, ledgered): the decidedness
  // clause was nested inside `if (cands.length >= 2)`, so a decisively-
  // ahead position with fewer than two cp-scored candidates emitted no
  // humility sentence at all -- exactly the shape ("decided positions")
  // this project keeps getting bitten by (winprob-delta-blind-to-decided-
  // positions). Decidedness must be computed from h.evalCp alone.
  it("Fix 2: a decisively-ahead position with only ONE cp-scored candidate still emits the decided-position sentence", async () => {
    const singleCandidate = [{ uci: "g1f3", evalCp: 810, evalMate: null }];
    const facts = assembleChatFactList(
      [],
      { mode: "live" },
      undefined, undefined, undefined, undefined,
      hintCandidateFacts(singleCandidate, 810) // |evalCp| >= HINT_DECIDED_CP; only 1 candidate -- no close call possible
    );
    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "this keeps the win comfortably.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("why this move?", [], facts, backend, { gameId, ply: 1, kind: "chat" });

    const margin = extractMargin(capturedPrompt);
    expect(margin).toBe(
      'the position is already decisively ahead for the side to move; several moves keep the win, so which winning move is "best" matters much less than usual.'
    );
    expect(margin).not.toMatch(/close call/i);
  });
});

// Round 3 (trace 126, old L2): the per-ply projection carries an explicit
// move-number fact alongside ply, so the coach can name "move 4" the way
// she reads a game instead of computing (or worse, stating) a raw ply
// count. Same "assert against the actual prompt string" discipline as the
// describe blocks above -- factsForModel is private.
describe("factsForModel — per-ply entries carry an explicit move number, not just raw ply (trace 126, L2)", () => {
  beforeEach(() => {
    openDb(":memory:");
  });

  it("ply 7 (white's 4th move) is labeled move 4 in the model-facing projection", async () => {
    const perPly: ChatPerPlyInput[] = [
      { ply: 7, san: "Nf3", evalCp: 20, evalMate: null, bestSan: "Nf3", pvSans: [] },
    ];
    const facts = assembleChatFactList([], {}, undefined, perPly);
    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "that develops your knight nicely.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("how did move 4 go?", [], facts, backend, { gameId, ply: 7, kind: "chat" });

    expect(capturedPrompt).toContain('"move":4');
  });

  it("ply 8 (mallow's 4th move) is ALSO labeled move 4 -- same pair, opposite side", async () => {
    const perPly: ChatPerPlyInput[] = [
      { ply: 8, san: "Nc6", evalCp: -20, evalMate: null, bestSan: "Nc6", pvSans: [] },
    ];
    const facts = assembleChatFactList([], {}, undefined, perPly);
    let capturedPrompt = "";
    const backend = fakeBackend(async (prompt) => {
      capturedPrompt = prompt;
      return "a natural developing reply.";
    });
    const sessionId = createSession();
    const gameId = createGame(sessionId, "maia-1100");
    await chat("what did she just play?", [], facts, backend, { gameId, ply: 8, kind: "chat" });

    expect(capturedPrompt).toContain('"move":4');
    expect(capturedPrompt).toContain('"side":"mallow"');
  });
});
