import { describe, it, expect, beforeEach } from "vitest";
import { assembleChatFactList, chat } from "./chat";
import type { ChatPerPlyInput } from "./chat";
import type { CoachBackend } from "./backends/types";
import { openDb, createSession, createGame } from "../store/db";

// Task 3 (R1a, fact-gap round): the chat surface previously never saw the
// judge's already-persisted per-ply engine analysis (moves.eval_cp/
// eval_mate/best_move/pv) at all -- it only ever had the bare san list
// (gameSans) and the CURRENT position. This is the load-bearing fix: thread
// the whole game's already-computed analysis in as an optional 4th param, so
// the coach can answer questions about EARLIER moments ("was my opening
// okay?") from real engine facts instead of reasoning about chess itself.
//
// UCI->SAN conversion for bestSan/pvSans happens in the CALLER (manager.ts,
// via the existing pvLine replay discipline) -- assembleChatFactList itself
// only tags each already-SAN entry with a phase and passes it through,
// mirroring the "derived, never hand-computed" rule the rest of this file
// follows, but for a fact this function receives pre-derived.

const moves = (sans: string[]) => sans.map((san, i) => ({ ply: i + 1, san }));

// Real game generated by scripted chess.js self-play (deterministic seed),
// captures biased so material actually drops -- ply 21 still has 24 pieces
// on the board (middlegame), ply 54 is down to 12 (endgame threshold).
const LONG_GAME = [
  "f4", "d6", "Nf3", "e6", "h3", "c6", "c4", "Qf6", "f5", "exf5", "h4", "Qxb2",
  "Bxb2", "f6", "Bxf6", "Nxf6", "Nd4", "Ne4", "Nxf5", "Nxd2", "Nxd2", "Bxf5",
  "Kf2", "Na6", "Qa4", "Bb1", "Rxb1", "Rd8", "Qxc6+", "bxc6", "h5", "Kf7",
  "g4", "Nc7", "e3", "Nd5", "cxd5", "cxd5", "Rb7+", "Kg8", "Rxa7", "h6",
  "Rxg7+", "Bxg7", "Bh3", "Kf7", "Rc1", "Rd7", "Re1", "Ra8", "g5", "Rxa2",
  "gxh6", "Bxh6",
];

describe("assembleChatFactList: perPlyAnalysis (Task 3, R1a)", () => {
  it("is absent when perPly is omitted (no behavior change for existing callers)", () => {
    const facts = assembleChatFactList(moves(LONG_GAME), {});
    expect(facts.perPlyAnalysis).toBeUndefined();
  });

  it("carries SAN best moves through untouched and tags ply 1 as opening (ply <= 20)", () => {
    const perPly = [
      { ply: 1, san: "f4", evalCp: 30, evalMate: null, bestSan: "d5", pvSans: ["d5", "Nf3"] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis).toEqual([
      { ply: 1, san: "f4", evalCp: 30, evalMate: null, bestSan: "d5", pvSans: ["d5", "Nf3"], phase: "opening" },
    ]);
  });

  it("tags a ply past 20 with more than 12 pieces on the board as middlegame", () => {
    const perPly = [
      { ply: 21, san: "Nxd2", evalCp: -50, evalMate: null, bestSan: "Bxf5", pvSans: ["Bxf5"] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].phase).toBe("middlegame");
  });

  it("tags a ply past 20 with 12 or fewer pieces on the board as endgame", () => {
    const perPly = [
      { ply: 54, san: "Bxh6", evalCp: 400, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].phase).toBe("endgame");
  });

  it("tags multiple plies independently in one call", () => {
    const perPly = [
      { ply: 1, san: "f4", evalCp: 30, evalMate: null, bestSan: "d5", pvSans: ["d5"] },
      { ply: 21, san: "Nxd2", evalCp: -50, evalMate: null, bestSan: "Bxf5", pvSans: ["Bxf5"] },
      { ply: 54, san: "Bxh6", evalCp: 400, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis!.map((p) => p.phase)).toEqual(["opening", "middlegame", "endgame"]);
  });

  it("a null bestSan/empty pvSans (no persisted eval yet for that ply) passes through as-is", () => {
    const perPly = [
      { ply: 54, san: "Bxh6", evalCp: null, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].bestSan).toBeNull();
    expect(facts.perPlyAnalysis![0].pvSans).toEqual([]);
  });
});

// Task 3b (R2, voice-enforcement round, 2026-07-22): factsForModel is
// private, so this asserts against the actual prompt string chat() sends
// the backend, the same pattern chat.hintFocus.test.ts/chat.test.ts's own
// prompt-inspection tests already use. evalCp/evalMate are SIDE-TO-MOVE
// signed as of the position AFTER the ply (same convention
// turningPoints.ts's buildDeltaSeries documents) -- an ODD ply's stored
// value is black-perspective and must be negated to reach the fixed
// "player is always white" read; an EVEN ply's is already white-perspective.
function fakeBackend(generate: (prompt: string, timeoutMs: number) => Promise<string>): CoachBackend {
  return {
    name: "fake",
    async available() {
      return true;
    },
    generate,
  };
}

const GAME = ["e4", "e5"];
const gameMoves = (sans: string[]) => sans.map((san, i) => ({ ply: i + 1, san }));

async function capturePerPlyPrompt(perPly: ChatPerPlyInput[]): Promise<string> {
  const facts = assembleChatFactList(gameMoves(GAME), { mode: "review" }, undefined, perPly);
  let capturedPrompt = "";
  const backend = fakeBackend(async (prompt) => {
    capturedPrompt = prompt;
    return "e4 is a fine start for you.";
  });
  const sessionId = createSession();
  const gameId = createGame(sessionId, "maia-1100");
  await chat("how did this go?", [], facts, backend, { gameId, ply: 1, kind: "chat" });
  return capturedPrompt;
}

describe("factsForModel — perPlyAnalysis's evalCp/evalMate sanitize into a qualitative 'read' bucket (Task 3b)", () => {
  beforeEach(() => {
    openDb(":memory:");
  });

  it("drops evalCp/evalMate (and any eval-named key) from the model projection, while the raw ChatFactList still carries the numbers", async () => {
    const perPly: ChatPerPlyInput[] = [
      { ply: 1, san: "e4", evalCp: 20, evalMate: null, bestSan: "e4", pvSans: [] },
    ];
    const facts = assembleChatFactList(gameMoves(GAME), { mode: "review" }, undefined, perPly);
    expect(facts.perPlyAnalysis?.[0].evalCp).toBe(20); // raw facts: numbers stay, for validation + F40 trace

    const prompt = await capturePerPlyPrompt(perPly);
    expect(prompt).toContain('"read"');
    expect(prompt).not.toContain('"evalCp"');
    expect(prompt).not.toContain('"evalMate"');
  });

  it("a small even-ply cp edge reads as 'even'", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: 20, evalMate: null, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain('"read": "even"');
  });

  it("a moderate even-ply positive cp reads as 'you're a bit better'", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: 150, evalMate: null, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read": "you're a bit better"`);
  });

  it("a large even-ply positive cp reads as 'you're much better'", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: 500, evalMate: null, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read": "you're much better"`);
  });

  it("a large even-ply negative cp reads as 'she's much better'", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: -500, evalMate: null, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read": "she's much better"`);
  });

  it("an ODD-ply negative cp (black's own stored perspective) negates to a white-favorable read", async () => {
    // Ply 1 is white's own move -- the stored eval afterward is from BLACK's
    // (side-to-move) perspective, so a stored -150 means white (the player)
    // is actually up 150: negation must run before bucketing.
    const prompt = await capturePerPlyPrompt([{ ply: 1, san: "e4", evalCp: -150, evalMate: null, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read": "you're a bit better"`);
  });

  it("an even-ply positive evalMate reads as 'mate for you in N'", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: null, evalMate: 3, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read": "mate for you in 3"`);
  });

  it("an even-ply negative evalMate reads as 'mate against you in N'", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: null, evalMate: -2, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read": "mate against you in 2"`);
  });

  it("an odd-ply evalMate is negated the same way evalCp is", async () => {
    // Ply 1: stored -4 is black's own perspective (black about to be mated
    // in 4 is wrong framing -- stored is black delivers in -4, i.e. black is
    // BEING mated) -- negating gives white (the player) mates in 4.
    const prompt = await capturePerPlyPrompt([{ ply: 1, san: "e4", evalCp: null, evalMate: -4, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain(`"read": "mate for you in 4"`);
  });

  it("no persisted eval yet for that ply (both null) reads as a plain no-data statement, never a number", async () => {
    const prompt = await capturePerPlyPrompt([{ ply: 2, san: "e5", evalCp: null, evalMate: null, bestSan: null, pvSans: [] }]);
    expect(prompt).toContain('"read": "no read yet"');
  });
});
