import { describe, it, expect } from "vitest";
import { assembleChatFactList } from "./chat";

// Task 3 (R1a, fact-gap round): the chat surface previously never saw the
// judge's already-persisted per-ply engine analysis (moves.eval_cp/
// eval_mate/best_move/pv) at all -- it only ever had the bare san list
// (gameSans) and the CURRENT position. This is the load-bearing fix: thread
// the whole game's already-computed analysis in as an optional 4th param, so
// the coach can answer questions about EARLIER moments ("was my opening
// okay?") from real engine facts instead of reasoning about chess itself.
//
// UCI->SAN conversion for bestSan/pvSans happens in the CALLER (manager.ts,
// via the existing pvLine replay discipline) -- assembleChatFactList itself
// only tags each already-SAN entry with a phase and passes it through,
// mirroring the "derived, never hand-computed" rule the rest of this file
// follows, but for a fact this function receives pre-derived.

const moves = (sans: string[]) => sans.map((san, i) => ({ ply: i + 1, san }));

// Real game generated by scripted chess.js self-play (deterministic seed),
// captures biased so material actually drops -- ply 21 still has 24 pieces
// on the board (middlegame), ply 54 is down to 12 (endgame threshold).
const LONG_GAME = [
  "f4", "d6", "Nf3", "e6", "h3", "c6", "c4", "Qf6", "f5", "exf5", "h4", "Qxb2",
  "Bxb2", "f6", "Bxf6", "Nxf6", "Nd4", "Ne4", "Nxf5", "Nxd2", "Nxd2", "Bxf5",
  "Kf2", "Na6", "Qa4", "Bb1", "Rxb1", "Rd8", "Qxc6+", "bxc6", "h5", "Kf7",
  "g4", "Nc7", "e3", "Nd5", "cxd5", "cxd5", "Rb7+", "Kg8", "Rxa7", "h6",
  "Rxg7+", "Bxg7", "Bh3", "Kf7", "Rc1", "Rd7", "Re1", "Ra8", "g5", "Rxa2",
  "gxh6", "Bxh6",
];

describe("assembleChatFactList: perPlyAnalysis (Task 3, R1a)", () => {
  it("is absent when perPly is omitted (no behavior change for existing callers)", () => {
    const facts = assembleChatFactList(moves(LONG_GAME), {});
    expect(facts.perPlyAnalysis).toBeUndefined();
  });

  it("carries SAN best moves through untouched and tags ply 1 as opening (ply <= 20)", () => {
    const perPly = [
      { ply: 1, san: "f4", evalCp: 30, evalMate: null, bestSan: "d5", pvSans: ["d5", "Nf3"] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis).toEqual([
      { ply: 1, san: "f4", evalCp: 30, evalMate: null, bestSan: "d5", pvSans: ["d5", "Nf3"], phase: "opening" },
    ]);
  });

  it("tags a ply past 20 with more than 12 pieces on the board as middlegame", () => {
    const perPly = [
      { ply: 21, san: "Nxd2", evalCp: -50, evalMate: null, bestSan: "Bxf5", pvSans: ["Bxf5"] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].phase).toBe("middlegame");
  });

  it("tags a ply past 20 with 12 or fewer pieces on the board as endgame", () => {
    const perPly = [
      { ply: 54, san: "Bxh6", evalCp: 400, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].phase).toBe("endgame");
  });

  it("tags multiple plies independently in one call", () => {
    const perPly = [
      { ply: 1, san: "f4", evalCp: 30, evalMate: null, bestSan: "d5", pvSans: ["d5"] },
      { ply: 21, san: "Nxd2", evalCp: -50, evalMate: null, bestSan: "Bxf5", pvSans: ["Bxf5"] },
      { ply: 54, san: "Bxh6", evalCp: 400, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis!.map((p) => p.phase)).toEqual(["opening", "middlegame", "endgame"]);
  });

  it("a null bestSan/empty pvSans (no persisted eval yet for that ply) passes through as-is", () => {
    const perPly = [
      { ply: 54, san: "Bxh6", evalCp: null, evalMate: null, bestSan: null, pvSans: [] },
    ];
    const facts = assembleChatFactList(moves(LONG_GAME), {}, undefined, perPly);
    expect(facts.perPlyAnalysis![0].bestSan).toBeNull();
    expect(facts.perPlyAnalysis![0].pvSans).toEqual([]);
  });
});
